// Code generated by ent, DO NOT EDIT.

package email

import (
	"theedashboard/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint) predicate.Email {
	return predicate.Email(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint) predicate.Email {
	return predicate.Email(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint) predicate.Email {
	return predicate.Email(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint) predicate.Email {
	return predicate.Email(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint) predicate.Email {
	return predicate.Email(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint) predicate.Email {
	return predicate.Email(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint) predicate.Email {
	return predicate.Email(sql.FieldLTE(FieldID, id))
}

// CallBackEmail applies equality check predicate on the "call_back_email" field. It's identical to CallBackEmailEQ.
func CallBackEmail(v string) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldCallBackEmail, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldMessage, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldName, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldSubject, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldUpdatedAt, v))
}

// CallBackEmailEQ applies the EQ predicate on the "call_back_email" field.
func CallBackEmailEQ(v string) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldCallBackEmail, v))
}

// CallBackEmailNEQ applies the NEQ predicate on the "call_back_email" field.
func CallBackEmailNEQ(v string) predicate.Email {
	return predicate.Email(sql.FieldNEQ(FieldCallBackEmail, v))
}

// CallBackEmailIn applies the In predicate on the "call_back_email" field.
func CallBackEmailIn(vs ...string) predicate.Email {
	return predicate.Email(sql.FieldIn(FieldCallBackEmail, vs...))
}

// CallBackEmailNotIn applies the NotIn predicate on the "call_back_email" field.
func CallBackEmailNotIn(vs ...string) predicate.Email {
	return predicate.Email(sql.FieldNotIn(FieldCallBackEmail, vs...))
}

// CallBackEmailGT applies the GT predicate on the "call_back_email" field.
func CallBackEmailGT(v string) predicate.Email {
	return predicate.Email(sql.FieldGT(FieldCallBackEmail, v))
}

// CallBackEmailGTE applies the GTE predicate on the "call_back_email" field.
func CallBackEmailGTE(v string) predicate.Email {
	return predicate.Email(sql.FieldGTE(FieldCallBackEmail, v))
}

// CallBackEmailLT applies the LT predicate on the "call_back_email" field.
func CallBackEmailLT(v string) predicate.Email {
	return predicate.Email(sql.FieldLT(FieldCallBackEmail, v))
}

// CallBackEmailLTE applies the LTE predicate on the "call_back_email" field.
func CallBackEmailLTE(v string) predicate.Email {
	return predicate.Email(sql.FieldLTE(FieldCallBackEmail, v))
}

// CallBackEmailContains applies the Contains predicate on the "call_back_email" field.
func CallBackEmailContains(v string) predicate.Email {
	return predicate.Email(sql.FieldContains(FieldCallBackEmail, v))
}

// CallBackEmailHasPrefix applies the HasPrefix predicate on the "call_back_email" field.
func CallBackEmailHasPrefix(v string) predicate.Email {
	return predicate.Email(sql.FieldHasPrefix(FieldCallBackEmail, v))
}

// CallBackEmailHasSuffix applies the HasSuffix predicate on the "call_back_email" field.
func CallBackEmailHasSuffix(v string) predicate.Email {
	return predicate.Email(sql.FieldHasSuffix(FieldCallBackEmail, v))
}

// CallBackEmailEqualFold applies the EqualFold predicate on the "call_back_email" field.
func CallBackEmailEqualFold(v string) predicate.Email {
	return predicate.Email(sql.FieldEqualFold(FieldCallBackEmail, v))
}

// CallBackEmailContainsFold applies the ContainsFold predicate on the "call_back_email" field.
func CallBackEmailContainsFold(v string) predicate.Email {
	return predicate.Email(sql.FieldContainsFold(FieldCallBackEmail, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.Email {
	return predicate.Email(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.Email {
	return predicate.Email(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.Email {
	return predicate.Email(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.Email {
	return predicate.Email(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.Email {
	return predicate.Email(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.Email {
	return predicate.Email(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.Email {
	return predicate.Email(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.Email {
	return predicate.Email(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.Email {
	return predicate.Email(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.Email {
	return predicate.Email(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageIsNil applies the IsNil predicate on the "message" field.
func MessageIsNil() predicate.Email {
	return predicate.Email(sql.FieldIsNull(FieldMessage))
}

// MessageNotNil applies the NotNil predicate on the "message" field.
func MessageNotNil() predicate.Email {
	return predicate.Email(sql.FieldNotNull(FieldMessage))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.Email {
	return predicate.Email(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.Email {
	return predicate.Email(sql.FieldContainsFold(FieldMessage, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Email {
	return predicate.Email(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Email {
	return predicate.Email(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Email {
	return predicate.Email(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Email {
	return predicate.Email(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Email {
	return predicate.Email(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Email {
	return predicate.Email(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Email {
	return predicate.Email(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Email {
	return predicate.Email(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Email {
	return predicate.Email(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Email {
	return predicate.Email(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Email {
	return predicate.Email(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Email {
	return predicate.Email(sql.FieldContainsFold(FieldName, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.Email {
	return predicate.Email(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.Email {
	return predicate.Email(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.Email {
	return predicate.Email(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.Email {
	return predicate.Email(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.Email {
	return predicate.Email(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.Email {
	return predicate.Email(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.Email {
	return predicate.Email(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.Email {
	return predicate.Email(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.Email {
	return predicate.Email(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.Email {
	return predicate.Email(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.Email {
	return predicate.Email(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.Email {
	return predicate.Email(sql.FieldContainsFold(FieldSubject, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Email {
	return predicate.Email(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Email {
	return predicate.Email(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.Email {
	return predicate.Email(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.Email {
	return predicate.Email(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Email {
	return predicate.Email(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Email {
	return predicate.Email(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Email {
	return predicate.Email(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Email {
	return predicate.Email(sql.FieldNotNull(FieldUpdatedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Email) predicate.Email {
	return predicate.Email(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Email) predicate.Email {
	return predicate.Email(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Email) predicate.Email {
	return predicate.Email(sql.NotPredicates(p))
}
