// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type AlembicVersion struct {
	ent.Schema
}

func (AlembicVersion) Fields() []ent.Field {
	return []ent.Field{field.String("id").StorageKey("version_num")}
}
func (AlembicVersion) Edges() []ent.Edge {
	return nil
}
func (AlembicVersion) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "alembic_version"}}
}
