// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type Email struct {
	ent.Schema
}

func (Email) Fields() []ent.Field {
	return []ent.Field{field.Uint("id").SchemaType(map[string]string{"postgres": "serial"}), field.String("call_back_email"), field.String("message").Optional(), field.String("name"), field.String("subject"), field.Time("created_at").Optional(), field.Time("updated_at").Optional()}
}
func (Email) Edges() []ent.Edge {
	return nil
}
func (Email) Annotations() []schema.Annotation {
	return nil
}
