// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Repository struct {
	ent.Schema
}

func (Repository) Fields() []ent.Field {
	return []ent.Field{field.Uint("id").SchemaType(map[string]string{"postgres": "serial"}), field.String("repo_name"), field.String("repo_description").Optional(), field.String("repo_url"), field.String("repo_language").Optional(), field.Time("repo_created_at"), field.Time("repo_updated_at"), field.Uint("user_id").Optional(), field.Time("created_at").Optional(), field.Time("updated_at").Optional(), field.Bool("show_on_profile"), field.Int32("order")}
}
func (Repository) Edges() []ent.Edge {
	return []ent.Edge{edge.From("user", User.Type).Ref("repositories").Unique().Field("user_id")}
}
func (Repository) Annotations() []schema.Annotation {
	return nil
}
