// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type User struct {
	ent.Schema
}

func (User) Fields() []ent.Field {
	return []ent.Field{field.Uint("id").SchemaType(map[string]string{"postgres": "serial"}), field.String("first_name").Optional(), field.String("last_name").Optional(), field.Time("dob").Optional(), field.String("username"), field.String("password"), field.String("email"), field.String("github_username").Optional(), field.String("description").Optional(), field.Time("created_at").Optional(), field.Time("updated_at").Optional(), field.Int32("mobile_number").Optional(), field.String("address_block").Optional(), field.String("address_street").Optional(), field.String("recidential_country").Optional(), field.String("nationality").Optional()}
}
func (User) Edges() []ent.Edge {
	return []ent.Edge{edge.To("educations", Education.Type), edge.To("experiences", Experience.Type), edge.To("repositories", Repository.Type), edge.To("user_projects", UserProject.Type), edge.To("user_services", UserService.Type), edge.To("user_skill_associations", UserSkillAssociation.Type)}
}
func (User) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "user"}}
}
