// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type UserProject struct {
	ent.Schema
}

func (UserProject) Fields() []ent.Field {
	return []ent.Field{field.Uint("id").SchemaType(map[string]string{"postgres": "serial"}), field.String("project_name"), field.Uint("user_id").Optional(), field.String("description").Optional(), field.Time("from_date").Optional(), field.Time("to_date").Optional(), field.String("project_link").Optional(), field.String("technologies").Optional(), field.Time("created_at").Optional(), field.Time("updated_at").Optional()}
}
func (UserProject) Edges() []ent.Edge {
	return []ent.Edge{edge.From("user", User.Type).Ref("user_projects").Unique().Field("user_id")}
}
func (UserProject) Annotations() []schema.Annotation {
	return nil
}
