// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"theedashboard/ent/alembicversion"
	"theedashboard/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AlembicVersionDelete is the builder for deleting a AlembicVersion entity.
type AlembicVersionDelete struct {
	config
	hooks    []Hook
	mutation *AlembicVersionMutation
}

// Where appends a list predicates to the AlembicVersionDelete builder.
func (avd *AlembicVersionDelete) Where(ps ...predicate.AlembicVersion) *AlembicVersionDelete {
	avd.mutation.Where(ps...)
	return avd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (avd *AlembicVersionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, avd.sqlExec, avd.mutation, avd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (avd *AlembicVersionDelete) ExecX(ctx context.Context) int {
	n, err := avd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (avd *AlembicVersionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(alembicversion.Table, sqlgraph.NewFieldSpec(alembicversion.FieldID, field.TypeString))
	if ps := avd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, avd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	avd.mutation.done = true
	return affected, err
}

// AlembicVersionDeleteOne is the builder for deleting a single AlembicVersion entity.
type AlembicVersionDeleteOne struct {
	avd *AlembicVersionDelete
}

// Where appends a list predicates to the AlembicVersionDelete builder.
func (avdo *AlembicVersionDeleteOne) Where(ps ...predicate.AlembicVersion) *AlembicVersionDeleteOne {
	avdo.avd.mutation.Where(ps...)
	return avdo
}

// Exec executes the deletion query.
func (avdo *AlembicVersionDeleteOne) Exec(ctx context.Context) error {
	n, err := avdo.avd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{alembicversion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (avdo *AlembicVersionDeleteOne) ExecX(ctx context.Context) {
	if err := avdo.Exec(ctx); err != nil {
		panic(err)
	}
}
