// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"theedashboard/ent/alembicversion"
	"theedashboard/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AlembicVersionQuery is the builder for querying AlembicVersion entities.
type AlembicVersionQuery struct {
	config
	ctx        *QueryContext
	order      []alembicversion.OrderOption
	inters     []Interceptor
	predicates []predicate.AlembicVersion
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AlembicVersionQuery builder.
func (avq *AlembicVersionQuery) Where(ps ...predicate.AlembicVersion) *AlembicVersionQuery {
	avq.predicates = append(avq.predicates, ps...)
	return avq
}

// Limit the number of records to be returned by this query.
func (avq *AlembicVersionQuery) Limit(limit int) *AlembicVersionQuery {
	avq.ctx.Limit = &limit
	return avq
}

// Offset to start from.
func (avq *AlembicVersionQuery) Offset(offset int) *AlembicVersionQuery {
	avq.ctx.Offset = &offset
	return avq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (avq *AlembicVersionQuery) Unique(unique bool) *AlembicVersionQuery {
	avq.ctx.Unique = &unique
	return avq
}

// Order specifies how the records should be ordered.
func (avq *AlembicVersionQuery) Order(o ...alembicversion.OrderOption) *AlembicVersionQuery {
	avq.order = append(avq.order, o...)
	return avq
}

// First returns the first AlembicVersion entity from the query.
// Returns a *NotFoundError when no AlembicVersion was found.
func (avq *AlembicVersionQuery) First(ctx context.Context) (*AlembicVersion, error) {
	nodes, err := avq.Limit(1).All(setContextOp(ctx, avq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{alembicversion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (avq *AlembicVersionQuery) FirstX(ctx context.Context) *AlembicVersion {
	node, err := avq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AlembicVersion ID from the query.
// Returns a *NotFoundError when no AlembicVersion ID was found.
func (avq *AlembicVersionQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = avq.Limit(1).IDs(setContextOp(ctx, avq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{alembicversion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (avq *AlembicVersionQuery) FirstIDX(ctx context.Context) string {
	id, err := avq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AlembicVersion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AlembicVersion entity is found.
// Returns a *NotFoundError when no AlembicVersion entities are found.
func (avq *AlembicVersionQuery) Only(ctx context.Context) (*AlembicVersion, error) {
	nodes, err := avq.Limit(2).All(setContextOp(ctx, avq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{alembicversion.Label}
	default:
		return nil, &NotSingularError{alembicversion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (avq *AlembicVersionQuery) OnlyX(ctx context.Context) *AlembicVersion {
	node, err := avq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AlembicVersion ID in the query.
// Returns a *NotSingularError when more than one AlembicVersion ID is found.
// Returns a *NotFoundError when no entities are found.
func (avq *AlembicVersionQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = avq.Limit(2).IDs(setContextOp(ctx, avq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{alembicversion.Label}
	default:
		err = &NotSingularError{alembicversion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (avq *AlembicVersionQuery) OnlyIDX(ctx context.Context) string {
	id, err := avq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AlembicVersions.
func (avq *AlembicVersionQuery) All(ctx context.Context) ([]*AlembicVersion, error) {
	ctx = setContextOp(ctx, avq.ctx, "All")
	if err := avq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AlembicVersion, *AlembicVersionQuery]()
	return withInterceptors[[]*AlembicVersion](ctx, avq, qr, avq.inters)
}

// AllX is like All, but panics if an error occurs.
func (avq *AlembicVersionQuery) AllX(ctx context.Context) []*AlembicVersion {
	nodes, err := avq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AlembicVersion IDs.
func (avq *AlembicVersionQuery) IDs(ctx context.Context) (ids []string, err error) {
	if avq.ctx.Unique == nil && avq.path != nil {
		avq.Unique(true)
	}
	ctx = setContextOp(ctx, avq.ctx, "IDs")
	if err = avq.Select(alembicversion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (avq *AlembicVersionQuery) IDsX(ctx context.Context) []string {
	ids, err := avq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (avq *AlembicVersionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, avq.ctx, "Count")
	if err := avq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, avq, querierCount[*AlembicVersionQuery](), avq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (avq *AlembicVersionQuery) CountX(ctx context.Context) int {
	count, err := avq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (avq *AlembicVersionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, avq.ctx, "Exist")
	switch _, err := avq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (avq *AlembicVersionQuery) ExistX(ctx context.Context) bool {
	exist, err := avq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AlembicVersionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (avq *AlembicVersionQuery) Clone() *AlembicVersionQuery {
	if avq == nil {
		return nil
	}
	return &AlembicVersionQuery{
		config:     avq.config,
		ctx:        avq.ctx.Clone(),
		order:      append([]alembicversion.OrderOption{}, avq.order...),
		inters:     append([]Interceptor{}, avq.inters...),
		predicates: append([]predicate.AlembicVersion{}, avq.predicates...),
		// clone intermediate query.
		sql:  avq.sql.Clone(),
		path: avq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (avq *AlembicVersionQuery) GroupBy(field string, fields ...string) *AlembicVersionGroupBy {
	avq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AlembicVersionGroupBy{build: avq}
	grbuild.flds = &avq.ctx.Fields
	grbuild.label = alembicversion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (avq *AlembicVersionQuery) Select(fields ...string) *AlembicVersionSelect {
	avq.ctx.Fields = append(avq.ctx.Fields, fields...)
	sbuild := &AlembicVersionSelect{AlembicVersionQuery: avq}
	sbuild.label = alembicversion.Label
	sbuild.flds, sbuild.scan = &avq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AlembicVersionSelect configured with the given aggregations.
func (avq *AlembicVersionQuery) Aggregate(fns ...AggregateFunc) *AlembicVersionSelect {
	return avq.Select().Aggregate(fns...)
}

func (avq *AlembicVersionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range avq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, avq); err != nil {
				return err
			}
		}
	}
	for _, f := range avq.ctx.Fields {
		if !alembicversion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if avq.path != nil {
		prev, err := avq.path(ctx)
		if err != nil {
			return err
		}
		avq.sql = prev
	}
	return nil
}

func (avq *AlembicVersionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AlembicVersion, error) {
	var (
		nodes = []*AlembicVersion{}
		_spec = avq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AlembicVersion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AlembicVersion{config: avq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, avq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (avq *AlembicVersionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := avq.querySpec()
	_spec.Node.Columns = avq.ctx.Fields
	if len(avq.ctx.Fields) > 0 {
		_spec.Unique = avq.ctx.Unique != nil && *avq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, avq.driver, _spec)
}

func (avq *AlembicVersionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(alembicversion.Table, alembicversion.Columns, sqlgraph.NewFieldSpec(alembicversion.FieldID, field.TypeString))
	_spec.From = avq.sql
	if unique := avq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if avq.path != nil {
		_spec.Unique = true
	}
	if fields := avq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, alembicversion.FieldID)
		for i := range fields {
			if fields[i] != alembicversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := avq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := avq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := avq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := avq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (avq *AlembicVersionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(avq.driver.Dialect())
	t1 := builder.Table(alembicversion.Table)
	columns := avq.ctx.Fields
	if len(columns) == 0 {
		columns = alembicversion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if avq.sql != nil {
		selector = avq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if avq.ctx.Unique != nil && *avq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range avq.predicates {
		p(selector)
	}
	for _, p := range avq.order {
		p(selector)
	}
	if offset := avq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := avq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AlembicVersionGroupBy is the group-by builder for AlembicVersion entities.
type AlembicVersionGroupBy struct {
	selector
	build *AlembicVersionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (avgb *AlembicVersionGroupBy) Aggregate(fns ...AggregateFunc) *AlembicVersionGroupBy {
	avgb.fns = append(avgb.fns, fns...)
	return avgb
}

// Scan applies the selector query and scans the result into the given value.
func (avgb *AlembicVersionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, avgb.build.ctx, "GroupBy")
	if err := avgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AlembicVersionQuery, *AlembicVersionGroupBy](ctx, avgb.build, avgb, avgb.build.inters, v)
}

func (avgb *AlembicVersionGroupBy) sqlScan(ctx context.Context, root *AlembicVersionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(avgb.fns))
	for _, fn := range avgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*avgb.flds)+len(avgb.fns))
		for _, f := range *avgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*avgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := avgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AlembicVersionSelect is the builder for selecting fields of AlembicVersion entities.
type AlembicVersionSelect struct {
	*AlembicVersionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (avs *AlembicVersionSelect) Aggregate(fns ...AggregateFunc) *AlembicVersionSelect {
	avs.fns = append(avs.fns, fns...)
	return avs
}

// Scan applies the selector query and scans the result into the given value.
func (avs *AlembicVersionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, avs.ctx, "Select")
	if err := avs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AlembicVersionQuery, *AlembicVersionSelect](ctx, avs.AlembicVersionQuery, avs, avs.inters, v)
}

func (avs *AlembicVersionSelect) sqlScan(ctx context.Context, root *AlembicVersionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(avs.fns))
	for _, fn := range avs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*avs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := avs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
