// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"theedashboard/ent/education"
	"theedashboard/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EducationCreate is the builder for creating a Education entity.
type EducationCreate struct {
	config
	mutation *EducationMutation
	hooks    []Hook
}

// SetInstitueName sets the "institue_name" field.
func (ec *EducationCreate) SetInstitueName(s string) *EducationCreate {
	ec.mutation.SetInstitueName(s)
	return ec
}

// SetStartDate sets the "start_date" field.
func (ec *EducationCreate) SetStartDate(t time.Time) *EducationCreate {
	ec.mutation.SetStartDate(t)
	return ec
}

// SetEndDate sets the "end_date" field.
func (ec *EducationCreate) SetEndDate(t time.Time) *EducationCreate {
	ec.mutation.SetEndDate(t)
	return ec
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (ec *EducationCreate) SetNillableEndDate(t *time.Time) *EducationCreate {
	if t != nil {
		ec.SetEndDate(*t)
	}
	return ec
}

// SetUserID sets the "user_id" field.
func (ec *EducationCreate) SetUserID(u uint) *EducationCreate {
	ec.mutation.SetUserID(u)
	return ec
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ec *EducationCreate) SetNillableUserID(u *uint) *EducationCreate {
	if u != nil {
		ec.SetUserID(*u)
	}
	return ec
}

// SetCreatedAt sets the "created_at" field.
func (ec *EducationCreate) SetCreatedAt(t time.Time) *EducationCreate {
	ec.mutation.SetCreatedAt(t)
	return ec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ec *EducationCreate) SetNillableCreatedAt(t *time.Time) *EducationCreate {
	if t != nil {
		ec.SetCreatedAt(*t)
	}
	return ec
}

// SetUpdatedAt sets the "updated_at" field.
func (ec *EducationCreate) SetUpdatedAt(t time.Time) *EducationCreate {
	ec.mutation.SetUpdatedAt(t)
	return ec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ec *EducationCreate) SetNillableUpdatedAt(t *time.Time) *EducationCreate {
	if t != nil {
		ec.SetUpdatedAt(*t)
	}
	return ec
}

// SetModeOfStudy sets the "mode_of_study" field.
func (ec *EducationCreate) SetModeOfStudy(s string) *EducationCreate {
	ec.mutation.SetModeOfStudy(s)
	return ec
}

// SetDegreeType sets the "degree_type" field.
func (ec *EducationCreate) SetDegreeType(s string) *EducationCreate {
	ec.mutation.SetDegreeType(s)
	return ec
}

// SetAreaOfStudy sets the "area_of_study" field.
func (ec *EducationCreate) SetAreaOfStudy(s string) *EducationCreate {
	ec.mutation.SetAreaOfStudy(s)
	return ec
}

// SetCurrentyStudying sets the "currenty_studying" field.
func (ec *EducationCreate) SetCurrentyStudying(b bool) *EducationCreate {
	ec.mutation.SetCurrentyStudying(b)
	return ec
}

// SetNillableCurrentyStudying sets the "currenty_studying" field if the given value is not nil.
func (ec *EducationCreate) SetNillableCurrentyStudying(b *bool) *EducationCreate {
	if b != nil {
		ec.SetCurrentyStudying(*b)
	}
	return ec
}

// SetDescription sets the "description" field.
func (ec *EducationCreate) SetDescription(s string) *EducationCreate {
	ec.mutation.SetDescription(s)
	return ec
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ec *EducationCreate) SetNillableDescription(s *string) *EducationCreate {
	if s != nil {
		ec.SetDescription(*s)
	}
	return ec
}

// SetID sets the "id" field.
func (ec *EducationCreate) SetID(u uint) *EducationCreate {
	ec.mutation.SetID(u)
	return ec
}

// SetUser sets the "user" edge to the User entity.
func (ec *EducationCreate) SetUser(u *User) *EducationCreate {
	return ec.SetUserID(u.ID)
}

// Mutation returns the EducationMutation object of the builder.
func (ec *EducationCreate) Mutation() *EducationMutation {
	return ec.mutation
}

// Save creates the Education in the database.
func (ec *EducationCreate) Save(ctx context.Context) (*Education, error) {
	return withHooks(ctx, ec.sqlSave, ec.mutation, ec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ec *EducationCreate) SaveX(ctx context.Context) *Education {
	v, err := ec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ec *EducationCreate) Exec(ctx context.Context) error {
	_, err := ec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ec *EducationCreate) ExecX(ctx context.Context) {
	if err := ec.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ec *EducationCreate) check() error {
	if _, ok := ec.mutation.InstitueName(); !ok {
		return &ValidationError{Name: "institue_name", err: errors.New(`ent: missing required field "Education.institue_name"`)}
	}
	if _, ok := ec.mutation.StartDate(); !ok {
		return &ValidationError{Name: "start_date", err: errors.New(`ent: missing required field "Education.start_date"`)}
	}
	if _, ok := ec.mutation.ModeOfStudy(); !ok {
		return &ValidationError{Name: "mode_of_study", err: errors.New(`ent: missing required field "Education.mode_of_study"`)}
	}
	if _, ok := ec.mutation.DegreeType(); !ok {
		return &ValidationError{Name: "degree_type", err: errors.New(`ent: missing required field "Education.degree_type"`)}
	}
	if _, ok := ec.mutation.AreaOfStudy(); !ok {
		return &ValidationError{Name: "area_of_study", err: errors.New(`ent: missing required field "Education.area_of_study"`)}
	}
	return nil
}

func (ec *EducationCreate) sqlSave(ctx context.Context) (*Education, error) {
	if err := ec.check(); err != nil {
		return nil, err
	}
	_node, _spec := ec.createSpec()
	if err := sqlgraph.CreateNode(ctx, ec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	ec.mutation.id = &_node.ID
	ec.mutation.done = true
	return _node, nil
}

func (ec *EducationCreate) createSpec() (*Education, *sqlgraph.CreateSpec) {
	var (
		_node = &Education{config: ec.config}
		_spec = sqlgraph.NewCreateSpec(education.Table, sqlgraph.NewFieldSpec(education.FieldID, field.TypeUint))
	)
	if id, ok := ec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ec.mutation.InstitueName(); ok {
		_spec.SetField(education.FieldInstitueName, field.TypeString, value)
		_node.InstitueName = value
	}
	if value, ok := ec.mutation.StartDate(); ok {
		_spec.SetField(education.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := ec.mutation.EndDate(); ok {
		_spec.SetField(education.FieldEndDate, field.TypeTime, value)
		_node.EndDate = value
	}
	if value, ok := ec.mutation.CreatedAt(); ok {
		_spec.SetField(education.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ec.mutation.UpdatedAt(); ok {
		_spec.SetField(education.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ec.mutation.ModeOfStudy(); ok {
		_spec.SetField(education.FieldModeOfStudy, field.TypeString, value)
		_node.ModeOfStudy = value
	}
	if value, ok := ec.mutation.DegreeType(); ok {
		_spec.SetField(education.FieldDegreeType, field.TypeString, value)
		_node.DegreeType = value
	}
	if value, ok := ec.mutation.AreaOfStudy(); ok {
		_spec.SetField(education.FieldAreaOfStudy, field.TypeString, value)
		_node.AreaOfStudy = value
	}
	if value, ok := ec.mutation.CurrentyStudying(); ok {
		_spec.SetField(education.FieldCurrentyStudying, field.TypeBool, value)
		_node.CurrentyStudying = value
	}
	if value, ok := ec.mutation.Description(); ok {
		_spec.SetField(education.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := ec.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   education.UserTable,
			Columns: []string{education.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EducationCreateBulk is the builder for creating many Education entities in bulk.
type EducationCreateBulk struct {
	config
	err      error
	builders []*EducationCreate
}

// Save creates the Education entities in the database.
func (ecb *EducationCreateBulk) Save(ctx context.Context) ([]*Education, error) {
	if ecb.err != nil {
		return nil, ecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ecb.builders))
	nodes := make([]*Education, len(ecb.builders))
	mutators := make([]Mutator, len(ecb.builders))
	for i := range ecb.builders {
		func(i int, root context.Context) {
			builder := ecb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EducationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ecb *EducationCreateBulk) SaveX(ctx context.Context) []*Education {
	v, err := ecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ecb *EducationCreateBulk) Exec(ctx context.Context) error {
	_, err := ecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecb *EducationCreateBulk) ExecX(ctx context.Context) {
	if err := ecb.Exec(ctx); err != nil {
		panic(err)
	}
}
