// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"theedashboard/ent/predicate"
	"theedashboard/ent/skill"
	"theedashboard/ent/userskillassociation"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SkillUpdate is the builder for updating Skill entities.
type SkillUpdate struct {
	config
	hooks    []Hook
	mutation *SkillMutation
}

// Where appends a list predicates to the SkillUpdate builder.
func (su *SkillUpdate) Where(ps ...predicate.Skill) *SkillUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetName sets the "name" field.
func (su *SkillUpdate) SetName(s string) *SkillUpdate {
	su.mutation.SetName(s)
	return su
}

// SetNillableName sets the "name" field if the given value is not nil.
func (su *SkillUpdate) SetNillableName(s *string) *SkillUpdate {
	if s != nil {
		su.SetName(*s)
	}
	return su
}

// SetCreatedAt sets the "created_at" field.
func (su *SkillUpdate) SetCreatedAt(t time.Time) *SkillUpdate {
	su.mutation.SetCreatedAt(t)
	return su
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (su *SkillUpdate) SetNillableCreatedAt(t *time.Time) *SkillUpdate {
	if t != nil {
		su.SetCreatedAt(*t)
	}
	return su
}

// ClearCreatedAt clears the value of the "created_at" field.
func (su *SkillUpdate) ClearCreatedAt() *SkillUpdate {
	su.mutation.ClearCreatedAt()
	return su
}

// SetUpdatedAt sets the "updated_at" field.
func (su *SkillUpdate) SetUpdatedAt(t time.Time) *SkillUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (su *SkillUpdate) SetNillableUpdatedAt(t *time.Time) *SkillUpdate {
	if t != nil {
		su.SetUpdatedAt(*t)
	}
	return su
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (su *SkillUpdate) ClearUpdatedAt() *SkillUpdate {
	su.mutation.ClearUpdatedAt()
	return su
}

// SetUserSkillAssociationID sets the "user_skill_association" edge to the UserSkillAssociation entity by ID.
func (su *SkillUpdate) SetUserSkillAssociationID(id uint) *SkillUpdate {
	su.mutation.SetUserSkillAssociationID(id)
	return su
}

// SetNillableUserSkillAssociationID sets the "user_skill_association" edge to the UserSkillAssociation entity by ID if the given value is not nil.
func (su *SkillUpdate) SetNillableUserSkillAssociationID(id *uint) *SkillUpdate {
	if id != nil {
		su = su.SetUserSkillAssociationID(*id)
	}
	return su
}

// SetUserSkillAssociation sets the "user_skill_association" edge to the UserSkillAssociation entity.
func (su *SkillUpdate) SetUserSkillAssociation(u *UserSkillAssociation) *SkillUpdate {
	return su.SetUserSkillAssociationID(u.ID)
}

// Mutation returns the SkillMutation object of the builder.
func (su *SkillUpdate) Mutation() *SkillMutation {
	return su.mutation
}

// ClearUserSkillAssociation clears the "user_skill_association" edge to the UserSkillAssociation entity.
func (su *SkillUpdate) ClearUserSkillAssociation() *SkillUpdate {
	su.mutation.ClearUserSkillAssociation()
	return su
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SkillUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SkillUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SkillUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SkillUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *SkillUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(skill.Table, skill.Columns, sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUint))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.SetField(skill.FieldName, field.TypeString, value)
	}
	if value, ok := su.mutation.CreatedAt(); ok {
		_spec.SetField(skill.FieldCreatedAt, field.TypeTime, value)
	}
	if su.mutation.CreatedAtCleared() {
		_spec.ClearField(skill.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.SetField(skill.FieldUpdatedAt, field.TypeTime, value)
	}
	if su.mutation.UpdatedAtCleared() {
		_spec.ClearField(skill.FieldUpdatedAt, field.TypeTime)
	}
	if su.mutation.UserSkillAssociationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   skill.UserSkillAssociationTable,
			Columns: []string{skill.UserSkillAssociationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userskillassociation.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.UserSkillAssociationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   skill.UserSkillAssociationTable,
			Columns: []string{skill.UserSkillAssociationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userskillassociation.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SkillUpdateOne is the builder for updating a single Skill entity.
type SkillUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SkillMutation
}

// SetName sets the "name" field.
func (suo *SkillUpdateOne) SetName(s string) *SkillUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (suo *SkillUpdateOne) SetNillableName(s *string) *SkillUpdateOne {
	if s != nil {
		suo.SetName(*s)
	}
	return suo
}

// SetCreatedAt sets the "created_at" field.
func (suo *SkillUpdateOne) SetCreatedAt(t time.Time) *SkillUpdateOne {
	suo.mutation.SetCreatedAt(t)
	return suo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (suo *SkillUpdateOne) SetNillableCreatedAt(t *time.Time) *SkillUpdateOne {
	if t != nil {
		suo.SetCreatedAt(*t)
	}
	return suo
}

// ClearCreatedAt clears the value of the "created_at" field.
func (suo *SkillUpdateOne) ClearCreatedAt() *SkillUpdateOne {
	suo.mutation.ClearCreatedAt()
	return suo
}

// SetUpdatedAt sets the "updated_at" field.
func (suo *SkillUpdateOne) SetUpdatedAt(t time.Time) *SkillUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (suo *SkillUpdateOne) SetNillableUpdatedAt(t *time.Time) *SkillUpdateOne {
	if t != nil {
		suo.SetUpdatedAt(*t)
	}
	return suo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (suo *SkillUpdateOne) ClearUpdatedAt() *SkillUpdateOne {
	suo.mutation.ClearUpdatedAt()
	return suo
}

// SetUserSkillAssociationID sets the "user_skill_association" edge to the UserSkillAssociation entity by ID.
func (suo *SkillUpdateOne) SetUserSkillAssociationID(id uint) *SkillUpdateOne {
	suo.mutation.SetUserSkillAssociationID(id)
	return suo
}

// SetNillableUserSkillAssociationID sets the "user_skill_association" edge to the UserSkillAssociation entity by ID if the given value is not nil.
func (suo *SkillUpdateOne) SetNillableUserSkillAssociationID(id *uint) *SkillUpdateOne {
	if id != nil {
		suo = suo.SetUserSkillAssociationID(*id)
	}
	return suo
}

// SetUserSkillAssociation sets the "user_skill_association" edge to the UserSkillAssociation entity.
func (suo *SkillUpdateOne) SetUserSkillAssociation(u *UserSkillAssociation) *SkillUpdateOne {
	return suo.SetUserSkillAssociationID(u.ID)
}

// Mutation returns the SkillMutation object of the builder.
func (suo *SkillUpdateOne) Mutation() *SkillMutation {
	return suo.mutation
}

// ClearUserSkillAssociation clears the "user_skill_association" edge to the UserSkillAssociation entity.
func (suo *SkillUpdateOne) ClearUserSkillAssociation() *SkillUpdateOne {
	suo.mutation.ClearUserSkillAssociation()
	return suo
}

// Where appends a list predicates to the SkillUpdate builder.
func (suo *SkillUpdateOne) Where(ps ...predicate.Skill) *SkillUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SkillUpdateOne) Select(field string, fields ...string) *SkillUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Skill entity.
func (suo *SkillUpdateOne) Save(ctx context.Context) (*Skill, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SkillUpdateOne) SaveX(ctx context.Context) *Skill {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SkillUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SkillUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *SkillUpdateOne) sqlSave(ctx context.Context) (_node *Skill, err error) {
	_spec := sqlgraph.NewUpdateSpec(skill.Table, skill.Columns, sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUint))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Skill.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, skill.FieldID)
		for _, f := range fields {
			if !skill.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != skill.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.SetField(skill.FieldName, field.TypeString, value)
	}
	if value, ok := suo.mutation.CreatedAt(); ok {
		_spec.SetField(skill.FieldCreatedAt, field.TypeTime, value)
	}
	if suo.mutation.CreatedAtCleared() {
		_spec.ClearField(skill.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.SetField(skill.FieldUpdatedAt, field.TypeTime, value)
	}
	if suo.mutation.UpdatedAtCleared() {
		_spec.ClearField(skill.FieldUpdatedAt, field.TypeTime)
	}
	if suo.mutation.UserSkillAssociationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   skill.UserSkillAssociationTable,
			Columns: []string{skill.UserSkillAssociationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userskillassociation.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.UserSkillAssociationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   skill.UserSkillAssociationTable,
			Columns: []string{skill.UserSkillAssociationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userskillassociation.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Skill{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
