// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"theedashboard/ent/predicate"
	"theedashboard/ent/userskillassociation"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserSkillAssociationDelete is the builder for deleting a UserSkillAssociation entity.
type UserSkillAssociationDelete struct {
	config
	hooks    []Hook
	mutation *UserSkillAssociationMutation
}

// Where appends a list predicates to the UserSkillAssociationDelete builder.
func (usad *UserSkillAssociationDelete) Where(ps ...predicate.UserSkillAssociation) *UserSkillAssociationDelete {
	usad.mutation.Where(ps...)
	return usad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (usad *UserSkillAssociationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, usad.sqlExec, usad.mutation, usad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (usad *UserSkillAssociationDelete) ExecX(ctx context.Context) int {
	n, err := usad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (usad *UserSkillAssociationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userskillassociation.Table, sqlgraph.NewFieldSpec(userskillassociation.FieldID, field.TypeUint))
	if ps := usad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, usad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	usad.mutation.done = true
	return affected, err
}

// UserSkillAssociationDeleteOne is the builder for deleting a single UserSkillAssociation entity.
type UserSkillAssociationDeleteOne struct {
	usad *UserSkillAssociationDelete
}

// Where appends a list predicates to the UserSkillAssociationDelete builder.
func (usado *UserSkillAssociationDeleteOne) Where(ps ...predicate.UserSkillAssociation) *UserSkillAssociationDeleteOne {
	usado.usad.mutation.Where(ps...)
	return usado
}

// Exec executes the deletion query.
func (usado *UserSkillAssociationDeleteOne) Exec(ctx context.Context) error {
	n, err := usado.usad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userskillassociation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (usado *UserSkillAssociationDeleteOne) ExecX(ctx context.Context) {
	if err := usado.Exec(ctx); err != nil {
		panic(err)
	}
}
